### ISSUE TITLE
1.5 Multiplayer issue

### ISSUE THREAD

**Issue by StellarHarbour** [Jaxe-Dev/RimHUD#13]
[RimHUD v1.15.1] Integrated mod 'Multiplayer' disabled due to the following exception:
cannot get method value without method.
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Warning (string)
RimHUD.Engine.Report:Warning (string)
RimHUD.Integration.IntegratedMod:DisableFrom (System.Exception)
RimHUD.Integration.Multiplayer.Mod_Multiplayer:.ctor ()
System.Reflection.MonoCMethod:InternalInvoke (object,object[])
System.RuntimeType:CreateInstanceMono (bool)
System.RuntimeType:CreateInstanceSlow (bool,bool,bool,System.Threading.StackCrawlMark&)
System.RuntimeType:CreateInstanceDefaultCtor (bool,bool,bool,System.Threading.StackCrawlMark&)
System.Activator:CreateInstance (System.Type,bool)
System.Activator:CreateInstance (System.Type)
RimHUD.Integration.Integrations:Load ()
RimHUD.Mod:OnStartup (HarmonyLib.Harmony)
RimHUD.Mod/<>c__DisplayClass14_0:<.ctor>b__0 ()
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.LongEventHandler.UpdateCurrentSynchronousEvent_Patch2 (bool&)
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root.Update_Patch1 (Verse.Root)
(wrapper dynamic-method) MonoMod.Utils.DynamicMethodDefinition:Verse.Root_Entry.Update_Patch0 (Verse.Root_Entry)

**Comment by Jaxe-Dev** [comment]
Fixed in 1.15.2
