### ISSUE TITLE
incompatibility with ProjectRimFactory

### ISSUE THREAD

**Issue by viewit000** [Jaxe-Dev/RimHUD#3]
I also encountered incompatibility with ProjectRimFactory.
The attached link has a screenshot about the issue.
https://github.com/spdskatr/ProjectRimFactory/issues/30
Thanks.

**Comment by DHandspikerWade** [comment]
It would be really nice to get this fixed. It's the only mod I've come across that causes an error.

**Comment by Jaxe-Dev** [comment]
RimHUD v1.4.0+ is more robust, this error may no longer occur.
