### ISSUE TITLE
meditating Active "multi line" , inspect display pane illegible issue

### ISSUE THREAD

**Issue by w-e-w** [Jaxe-Dev/RimHUD#5]
running RW 1.2 with "Royalty"

it seem like when the inspector try to display a 2 line element then it the mod thinks it's only 1 line cause issues
the mod is trying to display 2 line of text in 1 line, so makeing it illegible

I think this is add in "Royalty", theres some new Active that cause issues. (new to RM is I might be wrong)

using the defult configs
normal
![2020-09-02 21_32_01-RimWorld by Ludeon Studios 001779](https://user-images.githubusercontent.com/40751091/91991184-2d8e4600-ed65-11ea-829a-530abeb92e0d.png)
### when it try to display meditating Active (multi line)
![2020-09-02 21_26_14-RimWorld by Ludeon Studios 001775](https://user-images.githubusercontent.com/40751091/91991329-58789a00-ed65-11ea-9c87-4eec29eaf0c5.png)
velina hud for reference
![2020-09-02 21_20_43-RimWorld by Ludeon Studios 001772](https://user-images.githubusercontent.com/40751091/91991179-2c5d1900-ed65-11ea-8e65-285b6dfe95dc.png)
also happens when not docked
![2020-09-02 21_31_25-RimWorld by Ludeon Studios 001777](https://user-images.githubusercontent.com/40751091/91991189-2e26dc80-ed65-11ea-9a1a-794baa5f3b3b.png)
![2020-09-02 21_31_38-RimWorld by Ludeon Studios 001778](https://user-images.githubusercontent.com/40751091/91991188-2e26dc80-ed65-11ea-8c6f-0fc0f30a0def.png)
**I isolate it to the Active element, but I believe the same issue could happen elsewhere**
![2020-09-02 21_29_31-RimWorld by Ludeon Studios 001776](https://user-images.githubusercontent.com/40751091/91991191-2ebf7300-ed65-11ea-992d-59e4fdb2fe0b.png)

I was playing in chinese but I don't believe this is a factor (switch to english for the bug report)
also the same issue when useing chinese

**Comment by xalmat** [comment]
Present in English as well

**Comment by dougbenham** [comment]
Temporary solution:
- Set Inspect Pane => Pane Height to 338
- Set Description Text => Height to 200%

**Comment by Jaxe-Dev** [comment]
Fixed in v1.9.0
