### ISSUE TITLE
Lag spike fix

### ISSUE THREAD

**Issue by HAL-NINE-THOUSAND** [Jaxe-Dev/RimHUD#6]
Hi Jaxe,

Love the mod, it's very handy. It's always used when I'm on the Rim. 

I noticed on my game when the tab was showing I was having the game freeze for a moment each second. I had a look at the code and I think I've spotted the main culprits. 

On the GUIExtensions class there are two functions, SetTo and ResizedBy. These get called a lot and generate a new class each time which was making the GC kick in to clear it up. I changed them to have a cached value and it's helped a lot with FPS. 

If you'd like I can submit a PR for the changes or as there isn't much the code is here: 

```csharp
//Replace these
// public static GUIStyle SetTo(this GUIStyle self, int? size = null, TextAnchor? alignment = null, bool? wrap = null) => new GUIStyle(self) { fontSize = size ?? self.fontSize, alignment = alignment ?? self.alignment, wordWrap = wrap ?? self.wordWrap };
//public static GUIStyle ResizedBy(this GUIStyle self, int size = 0) => new GUIStyle(self) { fontSize = self.fontSize + size };

//with this
    private static GUIStyle SetToStyle;
        public static GUIStyle SetTo(this GUIStyle self, int? size = null, TextAnchor? alignment = null, bool? wrap = null)
        {
            
            SetToStyle = SetToStyle ?? new GUIStyle(self);
            SetToStyle.fontSize = size ?? self.fontSize;
            SetToStyle.alignment = alignment ?? self.alignment;
            SetToStyle.wordWrap = wrap ?? self.wordWrap;
            return SetToStyle;
        }
        private static GUIStyle ResizeStyle;
        public static GUIStyle ResizedBy(this GUIStyle self, int size = 0)
        {

            ResizeStyle = ResizeStyle ?? new GUIStyle(self);
            ResizeStyle.alignment = self.alignment;
            ResizeStyle.wordWrap = self.wordWrap;
            ResizeStyle.fontSize = self.fontSize + size;
            return ResizeStyle;
        }

```

Before:
![image](https://user-images.githubusercontent.com/2001016/92648034-c2062480-f2e0-11ea-932b-08547ce0d91c.png)

After:
![image](https://user-images.githubusercontent.com/2001016/92649592-2e822300-f2e3-11ea-8667-c5d8ecd4147d.png)

It's not perfect, it still spikes occasionally so there may be other allocations somewhere but it definitely helps smooth things out for my game. 

I've played with it for a while and can't spot any issues so thought I'd share it. 

Cheers,

Hal

**Comment by randonoob99** [comment]
Thanks for digging into this issue. When I tried this exact approach I was having text alignment issues but v1.6.8 should not be creating new GUIStyles and GUIContent each tick so hopefully this should be good now.

**Comment by Jaxe-Dev** [comment]
Thanks for investigating into this issue. While this exact approach was causing text alignment issues for me, I've now stopped new GUIStyles and GUIContents being created each tick so hopefully that should sort the lag spikes out.
