### ISSUE TITLE
RimHUD window height limit is too small

### ISSUE THREAD

**Issue by Acru** [Jaxe-Dev/RimHUD#7]
There is a hard height limit of 500 pixels for the hud window, even if the config file is edited directly, which isn't enough when floating with larger text and mod-added bars and info~

This limit should be relaxed at least, and moreso for the vertical-oriented floating pane, considering the high resolution monitors available these days. 

Would one just need to increase the height values in Theme.cs, or would there be more to it?

**Comment by Jaxe-Dev** [comment]
Late reply sorry, I've been away from the modding scene for a long while. I'll set this to 1500 for the next update, would this be about right or would more be useful?

**Comment by Jaxe-Dev** [comment]
Adjusted for v1.9.0

**Comment by Acru** [comment]
For my use-case that should be plenty, yes.

Though making this and other size values a soft-limit might future-proof it better, ie, allowing larger values to be manually entered.
